name: 💾Installation
description: Create a short report if you encoutered problems when installing the SAW.sif. Please write a comprehensive title after the 'Installation' prefix first. 
title: "Installation: "
labels: "Installation/environment"

body:
- type: markdown
  attributes:
    value: >
      #### Thank you for taking the time to report an installation problem. Before creating a new issue, please make sure to take a few minutes to check the issue tracker for [existing and past issues](https://github.com/BGIResearch/SAW/issues). 

