name: 💾Installation
description: Create a short report if you encoutered problems when installing the SAW.sif. Please write a comprehensive title after the 'Installation' prefix first. 
title: "Installation: "
labels: "Installation/environment"

body:
- type: markdown
  attributes:
    value: >
      #### Thank you for taking the time to report an installation problem. Before creating a new issue, please make sure to take a few minutes to check the issue tracker for [existing and past issues](https://github.com/BGIResearch/SAW/issues).

- type: textarea
  attributes: 
    description: "Please provide the order number for the STOmics chip(if possible):"
    label: "📝Order number for the STOmics chip(if possible):"
    placeholder: "SS200000***_** etc."
  validations:
    required: false

- type: dropdown
  id: Softwares
  attributes: 
    label: Which software are you having trouble installing?
    options:
      - Singularity
      - SAW.sif
      - others(describe them below)
 validations:
    required: true

- type: dropdown
  id: Permission
  attributes: 
    label: Your permissions on the server?
    options:
      - root
      - non-root user
 validations:
    required: true
  
- type: textarea
  attributes:
    label: "🌟Error message and context for the issue:"
    description: >
      Please include full error messages, if any. Screenshots of your error messages or the log files would be helpful! 
    placeholder: |
      ```
      Please provide more information about this issue including but not limited to:
      1) The versions of softwares you wanted to install
      2) The versions of softwares you used.(e.g. Please provide version of Singularity when having trouble installing SAW.sif)
      3) The install command
      4) The error messages you got, with the full traceback.
      ```
  validations:
    required: true

- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
