name: 💾Installation
description: Create a short report if you encoutered problems when installing the SAW.sif. Please write a comprehensive title after the 'Installation' prefix first. 
title: "Installation: "
labels: "Installation/environment"

body:
- type: markdown
  attributes:
    value: >
      #### Thank you for taking the time to report an installation problem. Before creating a new issue, please make sure to take a few minutes to check the issue tracker for [existing and past issues](https://github.com/BGIResearch/SAW/issues). 

- type: textarea
  attributes: 
    description: "Please provide the order number for the STOmics chip(if possible):"
    label: "📝Order number for the STOmics chip(if possible):"
    placeholder: "SS200000***_** etc."
  validations:
    required: false
    
- type: dropdown
  id: Softwares
  attributes: 
    label: Which software are you having trouble installing?
    options:
      - Singularity
      - SAW.sif
 validations:
    required: true
