name: 🚀Enhancement
description: Submit a proposal/request for progressively improving quality of our softwares. Please write a comprehensive title after the 'Enhancement' prefix first. 
title: "Enhancement: "
labels: "enahncement"

body:
- type: markdown
  attributes:
    value: >
      #### Thank you for taking the time to submit a proposal/request. Before creating a new issue, please make sure to take a few minutes to check the issue tracker for [existing and past issues](https://github.com/BGIResearch/SAW/issues).

- type: textarea
  attributes:
    label: 🚀The feature, motivation and pitch
    description: >
      A clear and concise description of the feature proposal. Please outline the motivation for the proposal. Is your feature request related to a specific problem? e.g., *"I'm working on X and would like Y to be possible"*. If this is related to another GitHub issue, please link here too.
  validations:
    required: true

- type: textarea
  attributes:
    label: 📚Alternatives
    description: >
      A description of any alternative solutions or features you've considered, if any.
      
- type: textarea
  attributes:
    label: 👍Additional context
    description: >
      Add any other context or screenshots about the feature request.
      
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
