name: 🐛Bug report
description: Create a report to help us solve the problem. Please write a comprehensive title after the 'Bug' prefix first. 
title: "Bug: "
labels: "bug"

body:
- type: markdown
  attributes:
    value: >
      #### Thank you for taking the time to file a bug report. Before creating a new issue, please make sure to take a few minutes to check the issue tracker for [existing and past issues](https://github.com/BGIResearch/SAW/issues).

- type: textarea
  attributes: 
    label: "🐛Bug description:"
    description: |
      Please provide a clear and concise description of what the bug is.
      If relevant, please add a example so that we can reproduce the bug by running the code. We are going to copy-paste your code and we expect to get the same result as you did.
    placeholder: |
      ```
      # Sample code to reproduce the problem
      ```
  validations:
    required: false
  
- type: textarea
  attributes: 
    description: "Please provide the order number for the STOmics chip(if possible):"
    label: "📝Order number for the STOmics chip(if possible):"
    placeholder: "SS200000***_** etc."
  validations:
    required: false

- type: textarea
  attributes:
    label: "⌨️Complete command used to run SAW:"
    description: "Please provide the complete command you used to run SAW:"
    placeholder: |
      sh <stereoRun.sh> -m maskFile -1 read1 -2 read2 -g indexedGenome -a annotationFile -o outDir -i image -t threads -s visualSif -c genomeSize
    render: shell
  validations:
    required: true
  
- type: textarea
  attributes:
    label: "🌟Error message and context for the issue:"
    description: >
      Please include full error messages, if any. Screenshots of your error messages or the log files would be helpful! 
    placeholder: |
      ```
      The error messages you got, with the full traceback.
      ```
  validations:
    required: true

- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
